baseURL = "https://dominicpm.github.io/"
languageCode = "en-gb"
title = "Dominic Mulligan"
theme = "noteworthy"
author = "Dominic Mulligan"
copyright = "Dominic Mulligan, 2020â€“2021"
enableRobotsTXT = true
publishDir = "docs"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    title = "Publications"
    url = "/publications/"
    weight = 0
